version: "3.3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/html:/usr/share/nginx/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - app-network

  django:
    build: .
    container_name: django
    #restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    command: sh -c "
      python3 manage.py migrate &&
      python3 manage.py runserver localhost:8080"


networks:
  app-network:
    driver: "bridge"
    external: false