version: "3.3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1; | psql -U postgres -d shop" ]
      interval: 3s
      timeout: 5s
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - db

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/html:/usr/share/nginx/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      django:
        condition: service_healthy

  django:
    build: .
    command: sh -c "
      python3 manage.py migrate &&
      python3 manage.py runserver localhost:8000"
    ports:
      - "8081:8000"
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/shop/"]
      interval: 3s
      timeout: 5s
    restart: unless-stopped

networks:
  db:
    driver: bridge
    #external: false