# Generated by Django 4.1.7 on 2023-04-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_pic', models.TextField(unique=True)),
                ('creation_date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'art',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_artist', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_city', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_client', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('client_password', models.TextField()),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_role', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'client_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_genre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
    ]
